[package]
name = "oxidetp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
data-encoding = "2.5.0"
hmac = "0.12.1"
sha1 = "0.10.6"
sha2 = "0.10.8"
thiserror = "2.0.16"
url = "2.5.0"

[dev-dependencies]
rstest = "0.26.1"
pretty_assertions = "1.4.0"

[workspace]
members = ["examples/*"]
